#!/bin/sh
#
# implementation to be tested

email_bre='^[A-Za-z]\{1,\}[A-Za-z0-9.]\{1,\}@[A-Za-z0-9]\{1,\}\(\.[A-Za-z0-9]\{1,\}\)\{1,\}$'

is_valid_email() {
	local email="$1" && shift
	if [ $(expr "$email" : "\($email_bre\)") ]; then
		return 0
	else
		return 1
	fi
}

get_user_name() {
	local email="$1" && shift
	if is_valid_email "$email"; then
		echo $(echo $email | cut -d'@' -f1)
	fi
}

get_domain_name() {
	local email="$1" && shift
	if is_valid_email "$email"; then
		echo $(echo $email | cut -d'@' -f2)
	fi
}
