# SHell Unit Test (SHUT) runner (https://github.com/lwalewski/shut.git)
# Copyright (c) 2017 Lukasz Walewski. All rights reserved.
# Distributed under the MIT License (http://opensource.org/licenses/MIT)

SHUT = ../src/shut
SHUT_SUITE = email-functions-test

test: $(SHUT_SUITE)
	$(SHUT) -s $<
