#!/bin/sh
#
# run test cases defined in the input file

OPTIONS=`getopt -o f: -n "$0" -- "$@"`

eval set -- "$OPTIONS"

while true; do
	case "$1" in
	-f)
		SHUT_SUITE="$2"
		shift 2
		;;
	--)
		shift
		break
		;;
	*)
		echo "*** internal error!"
		exit 1
		;;
	esac
done


die() {
	[ $# -gt 0 ] && echo "error: $@" >&2
	exit 1
}


messag_fmt="%-50s"
passed_fmt=" PASSED\n"
failed_fmt="*FAILED* (expected '%s' but got '%s')\n"

. $(dirname $0)/functions

if [ -r $SHUT_SUITE ]; then
	if ! is_path "$SHUT_SUITE"; then
		SHUT_SUITE="./$SHUT_SUITE"
	fi
	. $SHUT_SUITE
	ntests=$(echo "$SHUT_TESTS" | wc -w)
	echo "running "$ntests" test cases from '$SHUT_SUITE'"
	echo
else
	echo "*** could not read '$SHUT_SUITE'"
	exit 1
fi

npassed=0; nfailed=0; ntotal=0
for i in ${SHUT_TESTS}; do
	if $i; then
		npassed=$(expr "$npassed" + 1)
	else
		nfailed=$(expr "$nfailed" + 1)
	fi
	ntotal=$(expr "$ntotal" + 1)
done

echo
echo "Summary"
echo "-------"
echo "tests total..: $ntotal"
echo "tests passed.: $npassed"
echo "tests failed.: $nfailed"

[ $nfailed -eq 0 ]
return $?
